name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 14:40 运行一次, 中国时间 22:40
    - cron: '40 00 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: '2ad0928c9a554ab1af700b1941f3aca6'
          GP_TOKEN: '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'
          PUSH_TYPES: 'PushPlus'
          DO_NOT_REWARD: 'false'
          PUSHPLUS_TOKEN : '71d7db2f36b847ddba361979f68f6370'
